
import React from 'react';
import { Curriculum } from '../types';
import { BookOpen, Target, Clock, Layers, CheckCircle, Lightbulb, ClipboardList } from 'lucide-react';
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ResponsiveContainer } from 'recharts';

interface CurriculumDisplayProps {
  curriculum: Curriculum;
}

export const CurriculumDisplay: React.FC<CurriculumDisplayProps> = ({ curriculum }) => {
  // Prep radar chart data (mock mapping complexity or depth)
  const radarData = curriculum.modules.map(m => ({
    subject: m.title.length > 15 ? m.title.substring(0, 15) + '...' : m.title,
    depth: m.topics.length * 2,
    fullMark: 20,
  }));

  return (
    <div className="space-y-12 pb-20">
      {/* Header Section */}
      <section className="bg-white rounded-2xl p-8 border border-slate-200 shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
          <div>
            <h2 className="text-3xl font-bold text-slate-900 mb-2">{curriculum.title}</h2>
            <div className="flex flex-wrap gap-4 text-sm text-slate-500">
              <span className="flex items-center gap-1">
                <Layers className="w-4 h-4" /> {curriculum.level}
              </span>
              <span className="flex items-center gap-1">
                <Clock className="w-4 h-4" /> {curriculum.totalDuration}
              </span>
            </div>
          </div>
          <div className="flex gap-2">
             <span className="px-3 py-1 bg-indigo-50 text-indigo-700 rounded-full text-xs font-semibold uppercase tracking-wider">Generated by CurricuForge</span>
          </div>
        </div>
        <p className="text-slate-600 leading-relaxed text-lg italic border-l-4 border-indigo-200 pl-4">
          {curriculum.description}
        </p>
      </section>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Column: Modules */}
        <div className="lg:col-span-2 space-y-6">
          <div className="flex items-center gap-2 mb-4">
            <BookOpen className="text-indigo-600 w-6 h-6" />
            <h3 className="text-xl font-semibold text-slate-800">Module Structure</h3>
          </div>
          
          {curriculum.modules.map((module, idx) => (
            <div key={module.id} className="group bg-white rounded-xl border border-slate-200 overflow-hidden transition-all hover:shadow-md">
              <div className="bg-slate-50 px-6 py-4 flex justify-between items-center border-b border-slate-200">
                <div className="flex items-center gap-3">
                  <span className="w-8 h-8 rounded-full bg-indigo-600 text-white flex items-center justify-center text-sm font-bold">
                    {idx + 1}
                  </span>
                  <h4 className="font-bold text-slate-800">{module.title}</h4>
                </div>
                <span className="text-xs font-medium text-slate-500 bg-white px-2 py-1 rounded border border-slate-200">{module.duration}</span>
              </div>
              <div className="p-6">
                <p className="text-slate-600 mb-4 text-sm">{module.description}</p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {module.topics.map((topic, tidx) => (
                    <div key={tidx} className="flex items-start gap-2 text-sm text-slate-700 bg-indigo-50/30 p-2 rounded-md border border-indigo-100/50">
                      <CheckCircle className="w-4 h-4 text-emerald-500 mt-0.5 shrink-0" />
                      <span>{topic}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Right Column: Outcomes & Visualization */}
        <div className="space-y-8">
          {/* Learning Outcomes */}
          <section className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
            <div className="flex items-center gap-2 mb-6">
              <Target className="text-emerald-600 w-5 h-5" />
              <h3 className="text-lg font-semibold text-slate-800">Learning Outcomes</h3>
            </div>
            <div className="space-y-4">
              {curriculum.learningOutcomes.map((outcome) => (
                <div key={outcome.id} className="p-4 rounded-lg bg-emerald-50/50 border border-emerald-100">
                  <p className="text-sm text-slate-800 font-medium mb-2">{outcome.text}</p>
                  <div className="flex flex-wrap gap-1">
                    {outcome.mappedModules.map(mid => {
                      const mod = curriculum.modules.find(m => m.id === mid || m.title.includes(mid));
                      return mod ? (
                        <span key={mid} className="text-[10px] bg-white text-emerald-700 px-2 py-0.5 rounded border border-emerald-200">
                          {mod.title.substring(0, 15)}...
                        </span>
                      ) : null;
                    })}
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Curriculum Depth Analysis */}
          <section className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
             <div className="flex items-center gap-2 mb-6">
              <Layers className="text-amber-600 w-5 h-5" />
              <h3 className="text-lg font-semibold text-slate-800">Complexity Analysis</h3>
            </div>
            <div className="h-64 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <RadarChart cx="50%" cy="50%" outerRadius="80%" data={radarData}>
                  <PolarGrid stroke="#e2e8f0" />
                  <PolarAngleAxis dataKey="subject" tick={{ fontSize: 10, fill: '#64748b' }} />
                  <PolarRadiusAxis angle={30} domain={[0, 20]} axisLine={false} tick={false} />
                  <Radar
                    name="Module Depth"
                    dataKey="depth"
                    stroke="#4f46e5"
                    fill="#4f46e5"
                    fillOpacity={0.6}
                  />
                </RadarChart>
              </ResponsiveContainer>
            </div>
            <p className="text-[11px] text-center text-slate-400 mt-2">Visual weight based on topic density per module.</p>
          </section>

          {/* Assessment & Optimization */}
          <section className="bg-slate-900 rounded-xl p-6 text-white shadow-lg">
             <div className="flex items-center gap-2 mb-4">
              <ClipboardList className="text-indigo-400 w-5 h-5" />
              <h3 className="text-lg font-semibold">Assessment Strategy</h3>
            </div>
            <p className="text-slate-300 text-sm leading-relaxed mb-6">
              {curriculum.assessmentStrategy}
            </p>
            
            <hr className="border-slate-800 mb-6" />

            <div className="flex items-center gap-2 mb-4">
              <Lightbulb className="text-amber-400 w-5 h-5" />
              <h3 className="text-lg font-semibold">AI Recommendations</h3>
            </div>
            <ul className="space-y-3">
              {curriculum.recommendations.map((rec, i) => (
                <li key={i} className="flex items-start gap-2 text-xs text-slate-300">
                  <span className="text-indigo-400 font-bold">•</span>
                  {rec}
                </li>
              ))}
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};
